[".config/nvim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"
[".config/ranger/plugins/ranger-zoxide"]
    type = "git-repo"
    url = "https://github.com/jchook/ranger-zoxide.git"
    refreshPeriod = "168h"
[".config/ranger/plugins/ranger-fzf-filter"]
    type = "git-repo"
    url = "https://github.com/MuXiu1997/ranger-fzf-filter.git"
    refreshPeriod = "168h"
[".config/ranger/plugins/ranger-fzf-marks"]
    type = "git-repo"
    url = "https://github.com/laggardkernel/ranger-fzf-marks.git"
    refreshPeriod = "168h"
[".config/ranger/plugins/ranger-archives"]
    type = "git-repo"
    url = "https://github.com/maximtrp/ranger-archives.git"
    refreshPeriod = "168h"
[".config/ranger/plugins/ranger-cmus"]
    type = "git-repo"
    url = "https://github.com/maximtrp/ranger-cmus.git"
    refreshPeriod = "168h"
[".config/ranger/plugins/ranger-devicons"]
    type = "git-repo"
    url = "https://github.com/alexanderjeurissen/ranger_devicons.git"
    refreshPeriod = "168h"
[".config/rofi/themes/gruvbox"]
    type = "git-repo"
    url = "https://github.com/bardisty/gruvbox-rofi.git"
    refreshPeriod = "168h"
[".config/tmux/plugins/extrakto"]
    type = "git-repo"
    url = "https://github.com/laktak/extrakto.git"
    refreshPeriod = "168h"
[".config/tmux/plugins/tmux-copycat"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tmux-copycat.git"
    refreshPeriod = "168h"
[".config/tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm.git"
    refreshPeriod = "168h"
["Repos/h-m-m"]
    type = "git-repo"
    url = "https://github.com/nadrad/h-m-m.git"
 ["Repos/ytfzf"]
    type = "git-repo"
    url = "https://github.com/pystardust/ytfzf.git"
    refreshPeriod = "168h"
[".config/min/userscripts/yt-block.js"]
    type = "file"
    url = "https://raw.githubusercontent.com/alisanoelia/yt-block/main/yt-block.js"
    refreshPeriod = "168h"
 [".config/min/userscripts/dark-mode.js"]
    type = "file"
    url = "https://raw.githubusercontent.com/PalmerAL/min-dark-mode-userscript/master/dark-mode.js"
    refreshPeriod = "168h"
